version: '3.3'
volumes:
  mysql-db:
    driver: local
services:
  mysql:
    build: ./mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: always
    environment:
      MYSQL_DATABASE: skillMgr
      MYSQL_USER: skillMgr
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
      