version: '3.3'
volumes:
  mysql-db:
    driver: local
services:
  mysql:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: skillMgr
      MYSQL_USER: skillMgr
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - mysql-db:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
      